/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#include "main_dot_c_test.h"

#include "gtest/gtest.h"

namespace UTBot {
// Some tests for function 'is_prime' were skipped, as execution of function is out of timeout.

// Some tests for function 'bubbleSort' were skipped, as execution of function is out of timeout.



#pragma region regression
TEST(regression, is_prime_test_1)
{
    // Construct input
    int n = 3;

    // Expected output
    int expected = 1;

    // Trigger the function
    int actual = is_prime(n);

    // Check results
    EXPECT_EQ(expected, actual);
}

TEST(regression, bubbleSort_test_1)
{
    // Construct input
    int arr[10] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int n = 2;

    // Expected output
    // No output variable for void function

    // Trigger the function
    bubbleSort(arr, n);

    // Check results
    // No check results for void function

    // Check function parameters
    int expected_arr[10] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    for (int it_5_0 = 0; it_5_0 < 10; it_5_0 ++) {
        EXPECT_EQ(expected_arr[it_5_0], arr[it_5_0]);
    }
}

TEST(regression, bubbleSort_test_2)
{
    // Construct input
    int arr[10] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int n = 0;

    // Expected output
    // No output variable for void function

    // Trigger the function
    bubbleSort(arr, n);

    // Check results
    // No check results for void function

    // Check function parameters
    int expected_arr[10] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    for (int it_6_0 = 0; it_6_0 < 10; it_6_0 ++) {
        EXPECT_EQ(expected_arr[it_6_0], arr[it_6_0]);
    }
}

TEST(regression, main_test_1)
{

    // Expected output
    int expected = 0;

    // Trigger the function
    int actual = main();

    // Check results
    EXPECT_EQ(expected, actual);
}

#pragma endregion
#pragma region error
TEST(error, bubbleSort_test_3)
{
    // Construct input
    int arr[10] = {3, 3, 2, 2, 2, 2, 2, 2, 2, -1};
    int n = 262145;

    // Trigger the function
    bubbleSort(arr, n);

    FAIL() << "Unreachable point or the function was supposed to fail, but "
        "actually completed successfully. See the SARIF report for details.";
}

#pragma endregion
}
