/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#include "main_dot_c_test.h"

#include "gtest/gtest.h"

namespace UTBot
{
    // Some tests for function 'is_prime' were skipped, as execution of function is out of timeout.

#pragma region regression
    TEST(regression, is_prime_test_1)
    {
        // Construct input
        int n = 0;

        // Expected output
        int expected = 0;

        // Trigger the function
        int actual = is_prime(n);

        // Check results
        EXPECT_EQ(expected, actual);
    }

    TEST(regression, main_test_1)
    {

        // Expected output
        int expected = 0;

        // Trigger the function
        int actual = main();

        // Check resultsﬁ
        EXPECT_EQ(expected, actual);
    }

#pragma endregion
}
